### ISSUE TITLE
JS Tween Library

### ISSUE THREAD

**Issue by thegoldenmule** [enklu/enkluplayer#213]
Rather than tweening with heavy JS calls each frame, let's add a C# tweening library with a JS interface.

Here is an initial concept:

```
// creates a TweenJS object for a specific element's prop
var a = tw.vec3(el, "position")
	// required, sets value to tween to
	.to(vec3(1, 0, 0))
	// optional, defaults to linear
	.easing(tw.easing.CubicInOut)
	// optional, pass in your own easing function
	.ease(function(start, end, t) { ... })
	// optional, defaults to 1
	.duration(3)
	// optional, defaults to current value
	.from(vec3(0, 0, 0))
	// optional delay before start
	.delay(1)
	// optional, called when initial value has been set
	.onStart(function(val) { ... })
	// optional, called every frame after prop has been set
	.onUpdate(function(val) { ... })
	// optional, called after final value has been set
	.onComplete(function(val) { ... })
	// optional, specifies an AnimationCurveJS directly-- overrides easing equation
	.curve(curve)
	// optional, starts the tween
	.start();

// creates a TweenGroupJs object
tw.group(a, b, c)
	// optional, called when all tweens are complete
	.onComplete(function() { ... })
	// optional, delays before starting unstarted tweens
	.delay(1)
	// optional, starts all unstarted tweens in group
	.start();
```

**Comment by jsundra** [comment]
I like it! A few thoughts:

- There should be a `.cancel()` or `.stop()` so tweens can early out if they're interrupted.
- Maybe we'll want a `.pause()` and `.resume()`, so similar to the first point, we can have a little more flexibility over the lifetime of a tween.
- Repeat/Loop. It could take a bool or a specific number, so `.repeat(true)` or `.repeat(3)` would be valid. The thought behind this is that some `update` loops in play now that'd benefit from this just effectively tween in circles forever.

And similarly, for groups there would be control over all of the child tween lifetimes. I'm trying to think if it would make sense for a group to be able to repeat/loop. That one might be a bit tricky on what should happen if tweens a & b run once, c loops, and the entire group is set to loop - all with different durations.

**Comment by thegoldenmule** [comment]
* o.000 I like `cancel()`. Good idea.
* Let's add once we need it.
* I like the idea of repeating, I'm less sure on the interface. I don't like the opaqueness of `repeat(true)`, perhaps different methods for different types: `repeatTimes(4)`, `loop()`, `pingPong()`, etc.

Let's also make group changes in v2. I don't see that as a necessity.

**Comment by thegoldenmule** [comment]
Oops.

**Comment by thegoldenmule** [comment]
See #214

**Comment by thegoldenmule** [comment]
This has been implemented.
