### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by rolandsmeenk** [enklu/enkluplayer#296]
I just found this public repo after searching for the _HoloLens Shader Pack_ that I am selling on the AssetStore. According to the Unity Asset Store regulations you are not allowed to do that.
I suggest to make your repository private or remove the _HoloLens Shader Pack_ content from it.

kind regards,

Roland Smeenk

**Comment by thegoldenmule** [comment]
Thank you for spotting this issue @rolandsmeenk ! We will remove it asap! Very sorry about that, we did not mean to include it.

**Comment by thegoldenmule** [comment]
See https://github.com/enklu/enkluplayer/pull/297/

**Comment by thegoldenmule** [comment]
@rolandsmeenk Is this acceptable or would you like us to scrub our git history as well?

**Comment by rolandsmeenk** [comment]
@thegoldenmule Thanks for you quick response. This is fine.

**Comment by thegoldenmule** [comment]
Appreciate your patience on the matter. Thanks
